name: VSP using for loops

on:
    push:
      branches:
        - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script
      - name: Run VSPUsingForLoops.py file 
        run: |
          python VQESeparateParameter-VSP/VSPUsingForLoops.py

      # Step 5: Upload results (optional)
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: vqe-results
          path: vqe_on_single_machine.json
