name: VSP Orchestrator and workers

on:
  push:
    branches:
      - main

jobs:
  orchestrator:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run VQE Separated Parameter Orchestrator
        run: python VQESeparateParameter(VSP)/VQEOrchestrator.py
      - name: Upload final results
        uses: actions/upload-artifact@v3
        with:
          name: final-results
          path: final_results.txt

  worker:
    needs: orchestrator
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker-id: [1, 2, 3, 4, 5]  # Create 5 parallel jobs
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run VQE Separated Parameter Worker
        run: python VQESeparateParameter(VSP)/VQEWorker.py ${{ matrix.worker-id }}
      - name: Upload worker results
        uses: actions/upload-artifact@v3
        with:
          name: worker-results-${{ matrix.worker-id }}
          path: worker_output_${{ matrix.worker-id }}.txt